services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    ports:
      - "5442:5432"